### ISSUE TITLE
"enable fp8 training for U-Net" how to disable it?

### ISSUE THREAD

**Issue by RaySteve312** [kijai/ComfyUI-FluxTrainer#28] opened 2024-08-31 09:50 UTC
"enable fp8 training for U-Net" how to disable it? i want to use the original dev fp16 model to train loras.
![屏幕截图 2024-08-31 174917](https://github.com/user-attachments/assets/ca639e06-16cd-4552-a5ad-3ee4297eb9f1)

**Comment by kijai** [comment] 2024-08-31 10:46
Disable the fp8_base in the train init node.

**Comment by RaySteve312** [comment] 2024-08-31 12:22
> Disable the fp8_base in the train init node.
i tried. but it didn't change.
![屏幕截图 2024-08-31 201946](https://github.com/user-attachments/assets/97085955-9552-4ac4-aa37-ac5eac13cd36)

**Comment by kijai** [comment] 2024-08-31 13:50
Ok yeah there was a logic error caused by the addition of the clip_l training and it's precision parameters, which made the main model fp8 always. Should be fixed now.

**Comment by RaySteve312** [comment] 2024-08-31 17:20
> Ok yeah there was a logic error caused by the addition of the clip_l training and it's precision parameters, which made the main model fp8 always. Should be fixed now.

It works now! Greak work, thank you!

**Closed** 2024-08-31 17:53 UTC
